services:
  postgres:
    image: postgres:16
    container_name: postgres16_bdcurso
    restart: unless-stopped
    environment:
      POSTGRES_DB: curso_bd
      POSTGRES_USER: curso_user
      POSTGRES_PASSWORD: curso_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U curso_user -d curso_bd" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - bd_network

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: pgadmin_bdcurso
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@curso.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - bd_network

volumes:
  postgres_data:

networks:
  bd_network:
    driver: bridge